[package]
name = "chal11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbc = { path = "../../crates/cbc" }
ecb = { path = "../../crates/ecb" }
rand = "0.8.5"
